/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_testoutput_WRAP_H_
#define SWIG_testoutput_WRAP_H_

class SwigDirector_ITestCallBack2 : public ITestCallBack2, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_ITestCallBack2(JNIEnv *jenv);
    virtual ~SwigDirector_ITestCallBack2();
    virtual void Call(char (*buf)[201]);
    virtual void Call2(char const *buf);
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};


#endif
